# This file tells Render how to deploy the bot.

services:
  - type: web
    name: shahrestan-e-vahshi
    env: python
    # We now tell Render to run our custom build script instead of the default command.
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app --worker-class uvicorn.workers.UvicornWorker"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shahrestan-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEB_APP_URL
        sync: false

databases:
  - name: shahrestan-db
    databaseName: shahrestan_db
    user: shahrestan_user
