# render.yaml (Updated and Simplified)

services:
  - type: web
    name: shahrestan-e-vahshi
    env: python
    # We are back to the standard build command.
    # The pre-installed Rust in Render's environment will handle the rest.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --worker-class uvicorn.workers.UvicornWorker"
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shahrestan-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEB_APP_URL
        sync: false

databases:
  - name: shahrestan-db
    databaseName: shahrestan_db
    user: shahrestan_user
