# render.yaml (Docker Version)

services:
  - type: web
    name: shahrestan-e-vahshi
    # Tell Render to use Docker instead of the native Python environment
    env: docker
    healthCheckPath: /
    # The following settings are auto-detected from the Dockerfile
    # but can be specified for clarity if needed.
    # dockerfilePath: ./Dockerfile
    # dockerCommand: gunicorn app:app --bind 0.0.0.0:10000 --worker-class uvicorn.workers.UvicornWorker
    
    # Environment variables remain the same
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shahrestan-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEB_APP_URL
        sync: false

databases:
  - name: shahrestan-db
    databaseName: shahrestan_db
    user: shahrestan_user
